/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.SeleniumScriptRuntimeModule;
import org.xtext.example.SeleniumScriptStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SeleniumScriptIdeSetup extends SeleniumScriptStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SeleniumScriptRuntimeModule(), new SeleniumScriptIdeModule()));
	}
	
}
