/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.ide;


/**
 * Use this class to register ide components.
 */
public class SeleniumScriptIdeModule extends AbstractSeleniumScriptIdeModule {
}
