/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SeleniumScriptUiModule extends AbstractSeleniumScriptUiModule {

	public SeleniumScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
