/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.seleniumScript.ui.internal.SeleniumScriptActivator;

public class SeleniumScriptUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SeleniumScriptActivator.getInstance().getInjector("org.xtext.example.SeleniumScript");
	}

}
