/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.seleniumScript.ui.internal.SeleniumScriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SeleniumScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SeleniumScriptActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SeleniumScriptActivator activator = SeleniumScriptActivator.getInstance();
		return activator != null ? activator.getInjector(SeleniumScriptActivator.ORG_XTEXT_EXAMPLE_SELENIUMSCRIPT) : null;
	}

}
