/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSeleniumScriptScopeProvider extends DelegatingScopeProvider {
}
