/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
} // Action
