/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assert Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.AssertAction#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getAssertAction()
 * @model
 * @generated
 */
public interface AssertAction extends Action
{
  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(SelectorHas)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getAssertAction_Selector()
   * @model containment="true"
   * @generated
   */
  SelectorHas getSelector();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.AssertAction#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(SelectorHas value);

} // AssertAction
