/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goto Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.GotoAction#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getGotoAction()
 * @model
 * @generated
 */
public interface GotoAction extends Action
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getGotoAction_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.GotoAction#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

} // GotoAction
