/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.Model#getTests <em>Tests</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Tests</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.seleniumScript.Test}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tests</em>' containment reference list.
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getModel_Tests()
   * @model containment="true"
   * @generated
   */
  EList<Test> getTests();

} // Model
