/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.seleniumScript.SeleniumScriptFactory
 * @model kind="package"
 * @generated
 */
public interface SeleniumScriptPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seleniumScript";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/SeleniumScript";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seleniumScript";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeleniumScriptPackage eINSTANCE = org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.ModelImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Tests</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TESTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.TestImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getTest()
   * @generated
   */
  int TEST = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__NAME = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.ActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAction()
   * @generated
   */
  int ACTION = 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.GotoActionImpl <em>Goto Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.GotoActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getGotoAction()
   * @generated
   */
  int GOTO_ACTION = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_ACTION__URL = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Goto Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.ClickActionImpl <em>Click Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.ClickActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getClickAction()
   * @generated
   */
  int CLICK_ACTION = 4;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ACTION__SELECTOR = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.AssertActionImpl <em>Assert Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.AssertActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAssertAction()
   * @generated
   */
  int ASSERT_ACTION = 5;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_ACTION__SELECTOR = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assert Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.WriteActionImpl <em>Write Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.WriteActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getWriteAction()
   * @generated
   */
  int WRITE_ACTION = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_ACTION__VALUE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_ACTION__SELECTOR = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Write Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.SelectActionImpl <em>Select Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.SelectActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectAction()
   * @generated
   */
  int SELECT_ACTION = 7;

  /**
   * The feature id for the '<em><b>Option Selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ACTION__OPTION_SELECTOR = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ACTION__VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>And</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ACTION__AND = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ACTION__SELECTOR = ACTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Select Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.SelectorWithImpl <em>Selector With</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.SelectorWithImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectorWith()
   * @generated
   */
  int SELECTOR_WITH = 8;

  /**
   * The feature id for the '<em><b>Base selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_WITH__BASE_SELECTOR = 0;

  /**
   * The feature id for the '<em><b>W</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_WITH__W = 1;

  /**
   * The feature id for the '<em><b>And</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_WITH__AND = 2;

  /**
   * The number of structural features of the '<em>Selector With</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_WITH_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.WithImpl <em>With</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.WithImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getWith()
   * @generated
   */
  int WITH = 9;

  /**
   * The feature id for the '<em><b>With Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH__WITH_ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH__VALUE = 1;

  /**
   * The number of structural features of the '<em>With</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.WithAttributeImpl <em>With Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.WithAttributeImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getWithAttribute()
   * @generated
   */
  int WITH_ATTRIBUTE = 10;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH_ATTRIBUTE__ATTRIBUTE = 0;

  /**
   * The number of structural features of the '<em>With Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITH_ATTRIBUTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.AndImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAnd()
   * @generated
   */
  int AND = 11;

  /**
   * The feature id for the '<em><b>And Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__AND_ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__VALUE = 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.AndAttributeImpl <em>And Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.AndAttributeImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAndAttribute()
   * @generated
   */
  int AND_ATTRIBUTE = 12;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_ATTRIBUTE__ATTRIBUTE = 0;

  /**
   * The number of structural features of the '<em>And Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_ATTRIBUTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.SelectorHasImpl <em>Selector Has</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.SelectorHasImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectorHas()
   * @generated
   */
  int SELECTOR_HAS = 13;

  /**
   * The feature id for the '<em><b>Base selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_HAS__BASE_SELECTOR = 0;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_HAS__ATTRIBUTE = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_HAS__VALUE = 2;

  /**
   * The number of structural features of the '<em>Selector Has</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_HAS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.VariableActionImpl <em>Variable Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.VariableActionImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getVariableAction()
   * @generated
   */
  int VARIABLE_ACTION = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ACTION__NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Assignation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ACTION__ASSIGNATION = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.VariableAssignationImpl <em>Variable Assignation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.VariableAssignationImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getVariableAssignation()
   * @generated
   */
  int VARIABLE_ASSIGNATION = 15;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNATION__ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNATION__SELECTOR = 1;

  /**
   * The number of structural features of the '<em>Variable Assignation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.seleniumScript.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.seleniumScript.impl.ValueImpl
   * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getValue()
   * @generated
   */
  int VALUE = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.seleniumScript.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.seleniumScript.Model#getTests <em>Tests</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tests</em>'.
   * @see org.xtext.example.seleniumScript.Model#getTests()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tests();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.example.seleniumScript.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.Test#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.seleniumScript.Test#getName()
   * @see #getTest()
   * @generated
   */
  EAttribute getTest_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.seleniumScript.Test#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.seleniumScript.Test#getActions()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.seleniumScript.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.GotoAction <em>Goto Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto Action</em>'.
   * @see org.xtext.example.seleniumScript.GotoAction
   * @generated
   */
  EClass getGotoAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.GotoAction#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.seleniumScript.GotoAction#getUrl()
   * @see #getGotoAction()
   * @generated
   */
  EAttribute getGotoAction_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.ClickAction <em>Click Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click Action</em>'.
   * @see org.xtext.example.seleniumScript.ClickAction
   * @generated
   */
  EClass getClickAction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.ClickAction#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.example.seleniumScript.ClickAction#getSelector()
   * @see #getClickAction()
   * @generated
   */
  EReference getClickAction_Selector();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.AssertAction <em>Assert Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assert Action</em>'.
   * @see org.xtext.example.seleniumScript.AssertAction
   * @generated
   */
  EClass getAssertAction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.AssertAction#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.example.seleniumScript.AssertAction#getSelector()
   * @see #getAssertAction()
   * @generated
   */
  EReference getAssertAction_Selector();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.WriteAction <em>Write Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write Action</em>'.
   * @see org.xtext.example.seleniumScript.WriteAction
   * @generated
   */
  EClass getWriteAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.WriteAction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.WriteAction#getValue()
   * @see #getWriteAction()
   * @generated
   */
  EAttribute getWriteAction_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.WriteAction#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.example.seleniumScript.WriteAction#getSelector()
   * @see #getWriteAction()
   * @generated
   */
  EReference getWriteAction_Selector();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.SelectAction <em>Select Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Action</em>'.
   * @see org.xtext.example.seleniumScript.SelectAction
   * @generated
   */
  EClass getSelectAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.SelectAction#isOptionSelector <em>Option Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Option Selector</em>'.
   * @see org.xtext.example.seleniumScript.SelectAction#isOptionSelector()
   * @see #getSelectAction()
   * @generated
   */
  EAttribute getSelectAction_OptionSelector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.SelectAction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.SelectAction#getValue()
   * @see #getSelectAction()
   * @generated
   */
  EAttribute getSelectAction_Value();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.seleniumScript.SelectAction#getAnd <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>And</em>'.
   * @see org.xtext.example.seleniumScript.SelectAction#getAnd()
   * @see #getSelectAction()
   * @generated
   */
  EReference getSelectAction_And();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.SelectAction#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.example.seleniumScript.SelectAction#getSelector()
   * @see #getSelectAction()
   * @generated
   */
  EReference getSelectAction_Selector();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.SelectorWith <em>Selector With</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector With</em>'.
   * @see org.xtext.example.seleniumScript.SelectorWith
   * @generated
   */
  EClass getSelectorWith();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.SelectorWith#getBase_selector <em>Base selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base selector</em>'.
   * @see org.xtext.example.seleniumScript.SelectorWith#getBase_selector()
   * @see #getSelectorWith()
   * @generated
   */
  EAttribute getSelectorWith_Base_selector();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.SelectorWith#getW <em>W</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>W</em>'.
   * @see org.xtext.example.seleniumScript.SelectorWith#getW()
   * @see #getSelectorWith()
   * @generated
   */
  EReference getSelectorWith_W();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.seleniumScript.SelectorWith#getAnd <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>And</em>'.
   * @see org.xtext.example.seleniumScript.SelectorWith#getAnd()
   * @see #getSelectorWith()
   * @generated
   */
  EReference getSelectorWith_And();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.With <em>With</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>With</em>'.
   * @see org.xtext.example.seleniumScript.With
   * @generated
   */
  EClass getWith();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.With#getWithAttribute <em>With Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>With Attribute</em>'.
   * @see org.xtext.example.seleniumScript.With#getWithAttribute()
   * @see #getWith()
   * @generated
   */
  EReference getWith_WithAttribute();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.With#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.With#getValue()
   * @see #getWith()
   * @generated
   */
  EReference getWith_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.WithAttribute <em>With Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>With Attribute</em>'.
   * @see org.xtext.example.seleniumScript.WithAttribute
   * @generated
   */
  EClass getWithAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.WithAttribute#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see org.xtext.example.seleniumScript.WithAttribute#getAttribute()
   * @see #getWithAttribute()
   * @generated
   */
  EAttribute getWithAttribute_Attribute();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.xtext.example.seleniumScript.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.And#getAndAttribute <em>And Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>And Attribute</em>'.
   * @see org.xtext.example.seleniumScript.And#getAndAttribute()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_AndAttribute();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.And#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.And#getValue()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.AndAttribute <em>And Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Attribute</em>'.
   * @see org.xtext.example.seleniumScript.AndAttribute
   * @generated
   */
  EClass getAndAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.AndAttribute#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see org.xtext.example.seleniumScript.AndAttribute#getAttribute()
   * @see #getAndAttribute()
   * @generated
   */
  EAttribute getAndAttribute_Attribute();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.SelectorHas <em>Selector Has</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector Has</em>'.
   * @see org.xtext.example.seleniumScript.SelectorHas
   * @generated
   */
  EClass getSelectorHas();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.SelectorHas#getBase_selector <em>Base selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base selector</em>'.
   * @see org.xtext.example.seleniumScript.SelectorHas#getBase_selector()
   * @see #getSelectorHas()
   * @generated
   */
  EAttribute getSelectorHas_Base_selector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.SelectorHas#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see org.xtext.example.seleniumScript.SelectorHas#getAttribute()
   * @see #getSelectorHas()
   * @generated
   */
  EAttribute getSelectorHas_Attribute();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.SelectorHas#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.SelectorHas#getValue()
   * @see #getSelectorHas()
   * @generated
   */
  EReference getSelectorHas_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.VariableAction <em>Variable Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Action</em>'.
   * @see org.xtext.example.seleniumScript.VariableAction
   * @generated
   */
  EClass getVariableAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.VariableAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.seleniumScript.VariableAction#getName()
   * @see #getVariableAction()
   * @generated
   */
  EAttribute getVariableAction_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.VariableAction#getAssignation <em>Assignation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Assignation</em>'.
   * @see org.xtext.example.seleniumScript.VariableAction#getAssignation()
   * @see #getVariableAction()
   * @generated
   */
  EReference getVariableAction_Assignation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.VariableAssignation <em>Variable Assignation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Assignation</em>'.
   * @see org.xtext.example.seleniumScript.VariableAssignation
   * @generated
   */
  EClass getVariableAssignation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.seleniumScript.VariableAssignation#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see org.xtext.example.seleniumScript.VariableAssignation#getAttribute()
   * @see #getVariableAssignation()
   * @generated
   */
  EAttribute getVariableAssignation_Attribute();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.seleniumScript.VariableAssignation#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.example.seleniumScript.VariableAssignation#getSelector()
   * @see #getVariableAssignation()
   * @generated
   */
  EReference getVariableAssignation_Selector();

  /**
   * Returns the meta object for class '{@link org.xtext.example.seleniumScript.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.seleniumScript.Value#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Value</em>'.
   * @see org.xtext.example.seleniumScript.Value#getValue()
   * @see #getValue()
   * @generated
   */
  EReference getValue_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeleniumScriptFactory getSeleniumScriptFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.ModelImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Tests</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TESTS = eINSTANCE.getModel_Tests();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.TestImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST__NAME = eINSTANCE.getTest_Name();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__ACTIONS = eINSTANCE.getTest_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.ActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.GotoActionImpl <em>Goto Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.GotoActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getGotoAction()
     * @generated
     */
    EClass GOTO_ACTION = eINSTANCE.getGotoAction();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOTO_ACTION__URL = eINSTANCE.getGotoAction_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.ClickActionImpl <em>Click Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.ClickActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getClickAction()
     * @generated
     */
    EClass CLICK_ACTION = eINSTANCE.getClickAction();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK_ACTION__SELECTOR = eINSTANCE.getClickAction_Selector();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.AssertActionImpl <em>Assert Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.AssertActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAssertAction()
     * @generated
     */
    EClass ASSERT_ACTION = eINSTANCE.getAssertAction();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERT_ACTION__SELECTOR = eINSTANCE.getAssertAction_Selector();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.WriteActionImpl <em>Write Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.WriteActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getWriteAction()
     * @generated
     */
    EClass WRITE_ACTION = eINSTANCE.getWriteAction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_ACTION__VALUE = eINSTANCE.getWriteAction_Value();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WRITE_ACTION__SELECTOR = eINSTANCE.getWriteAction_Selector();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.SelectActionImpl <em>Select Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.SelectActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectAction()
     * @generated
     */
    EClass SELECT_ACTION = eINSTANCE.getSelectAction();

    /**
     * The meta object literal for the '<em><b>Option Selector</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_ACTION__OPTION_SELECTOR = eINSTANCE.getSelectAction_OptionSelector();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_ACTION__VALUE = eINSTANCE.getSelectAction_Value();

    /**
     * The meta object literal for the '<em><b>And</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_ACTION__AND = eINSTANCE.getSelectAction_And();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_ACTION__SELECTOR = eINSTANCE.getSelectAction_Selector();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.SelectorWithImpl <em>Selector With</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.SelectorWithImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectorWith()
     * @generated
     */
    EClass SELECTOR_WITH = eINSTANCE.getSelectorWith();

    /**
     * The meta object literal for the '<em><b>Base selector</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR_WITH__BASE_SELECTOR = eINSTANCE.getSelectorWith_Base_selector();

    /**
     * The meta object literal for the '<em><b>W</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR_WITH__W = eINSTANCE.getSelectorWith_W();

    /**
     * The meta object literal for the '<em><b>And</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR_WITH__AND = eINSTANCE.getSelectorWith_And();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.WithImpl <em>With</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.WithImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getWith()
     * @generated
     */
    EClass WITH = eINSTANCE.getWith();

    /**
     * The meta object literal for the '<em><b>With Attribute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WITH__WITH_ATTRIBUTE = eINSTANCE.getWith_WithAttribute();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WITH__VALUE = eINSTANCE.getWith_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.WithAttributeImpl <em>With Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.WithAttributeImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getWithAttribute()
     * @generated
     */
    EClass WITH_ATTRIBUTE = eINSTANCE.getWithAttribute();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WITH_ATTRIBUTE__ATTRIBUTE = eINSTANCE.getWithAttribute_Attribute();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.AndImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>And Attribute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__AND_ATTRIBUTE = eINSTANCE.getAnd_AndAttribute();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__VALUE = eINSTANCE.getAnd_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.AndAttributeImpl <em>And Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.AndAttributeImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getAndAttribute()
     * @generated
     */
    EClass AND_ATTRIBUTE = eINSTANCE.getAndAttribute();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_ATTRIBUTE__ATTRIBUTE = eINSTANCE.getAndAttribute_Attribute();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.SelectorHasImpl <em>Selector Has</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.SelectorHasImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getSelectorHas()
     * @generated
     */
    EClass SELECTOR_HAS = eINSTANCE.getSelectorHas();

    /**
     * The meta object literal for the '<em><b>Base selector</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR_HAS__BASE_SELECTOR = eINSTANCE.getSelectorHas_Base_selector();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR_HAS__ATTRIBUTE = eINSTANCE.getSelectorHas_Attribute();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR_HAS__VALUE = eINSTANCE.getSelectorHas_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.VariableActionImpl <em>Variable Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.VariableActionImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getVariableAction()
     * @generated
     */
    EClass VARIABLE_ACTION = eINSTANCE.getVariableAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_ACTION__NAME = eINSTANCE.getVariableAction_Name();

    /**
     * The meta object literal for the '<em><b>Assignation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_ACTION__ASSIGNATION = eINSTANCE.getVariableAction_Assignation();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.VariableAssignationImpl <em>Variable Assignation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.VariableAssignationImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getVariableAssignation()
     * @generated
     */
    EClass VARIABLE_ASSIGNATION = eINSTANCE.getVariableAssignation();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_ASSIGNATION__ATTRIBUTE = eINSTANCE.getVariableAssignation_Attribute();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_ASSIGNATION__SELECTOR = eINSTANCE.getVariableAssignation_Selector();

    /**
     * The meta object literal for the '{@link org.xtext.example.seleniumScript.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.seleniumScript.impl.ValueImpl
     * @see org.xtext.example.seleniumScript.impl.SeleniumScriptPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__VALUE = eINSTANCE.getValue_Value();

  }

} //SeleniumScriptPackage
