/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.SelectAction#isOptionSelector <em>Option Selector</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectAction#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectAction#getAnd <em>And</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectAction#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectAction()
 * @model
 * @generated
 */
public interface SelectAction extends Action
{
  /**
   * Returns the value of the '<em><b>Option Selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Option Selector</em>' attribute.
   * @see #setOptionSelector(boolean)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectAction_OptionSelector()
   * @model
   * @generated
   */
  boolean isOptionSelector();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectAction#isOptionSelector <em>Option Selector</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Option Selector</em>' attribute.
   * @see #isOptionSelector()
   * @generated
   */
  void setOptionSelector(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectAction_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectAction#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>And</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.seleniumScript.And}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And</em>' containment reference list.
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectAction_And()
   * @model containment="true"
   * @generated
   */
  EList<And> getAnd();

  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(SelectorWith)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectAction_Selector()
   * @model containment="true"
   * @generated
   */
  SelectorWith getSelector();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectAction#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(SelectorWith value);

} // SelectAction
