/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selector Has</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.SelectorHas#getBase_selector <em>Base selector</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectorHas#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectorHas#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorHas()
 * @model
 * @generated
 */
public interface SelectorHas extends EObject
{
  /**
   * Returns the value of the '<em><b>Base selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base selector</em>' attribute.
   * @see #setBase_selector(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorHas_Base_selector()
   * @model
   * @generated
   */
  String getBase_selector();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectorHas#getBase_selector <em>Base selector</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base selector</em>' attribute.
   * @see #getBase_selector()
   * @generated
   */
  void setBase_selector(String value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' attribute.
   * @see #setAttribute(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorHas_Attribute()
   * @model
   * @generated
   */
  String getAttribute();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectorHas#getAttribute <em>Attribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' attribute.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Value)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorHas_Value()
   * @model containment="true"
   * @generated
   */
  Value getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectorHas#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Value value);

} // SelectorHas
