/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selector With</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.SelectorWith#getBase_selector <em>Base selector</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectorWith#getW <em>W</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.SelectorWith#getAnd <em>And</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorWith()
 * @model
 * @generated
 */
public interface SelectorWith extends EObject
{
  /**
   * Returns the value of the '<em><b>Base selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base selector</em>' attribute.
   * @see #setBase_selector(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorWith_Base_selector()
   * @model
   * @generated
   */
  String getBase_selector();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectorWith#getBase_selector <em>Base selector</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base selector</em>' attribute.
   * @see #getBase_selector()
   * @generated
   */
  void setBase_selector(String value);

  /**
   * Returns the value of the '<em><b>W</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' containment reference.
   * @see #setW(With)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorWith_W()
   * @model containment="true"
   * @generated
   */
  With getW();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.SelectorWith#getW <em>W</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>W</em>' containment reference.
   * @see #getW()
   * @generated
   */
  void setW(With value);

  /**
   * Returns the value of the '<em><b>And</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.seleniumScript.And}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And</em>' containment reference list.
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getSelectorWith_And()
   * @model containment="true"
   * @generated
   */
  EList<And> getAnd();

} // SelectorWith
