/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.VariableAction#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.VariableAction#getAssignation <em>Assignation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getVariableAction()
 * @model
 * @generated
 */
public interface VariableAction extends Action
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getVariableAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.VariableAction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Assignation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignation</em>' containment reference.
   * @see #setAssignation(VariableAssignation)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getVariableAction_Assignation()
   * @model containment="true"
   * @generated
   */
  VariableAssignation getAssignation();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.VariableAction#getAssignation <em>Assignation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignation</em>' containment reference.
   * @see #getAssignation()
   * @generated
   */
  void setAssignation(VariableAssignation value);

} // VariableAction
