/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>With</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.With#getWithAttribute <em>With Attribute</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.With#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getWith()
 * @model
 * @generated
 */
public interface With extends EObject
{
  /**
   * Returns the value of the '<em><b>With Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Attribute</em>' containment reference.
   * @see #setWithAttribute(WithAttribute)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getWith_WithAttribute()
   * @model containment="true"
   * @generated
   */
  WithAttribute getWithAttribute();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.With#getWithAttribute <em>With Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With Attribute</em>' containment reference.
   * @see #getWithAttribute()
   * @generated
   */
  void setWithAttribute(WithAttribute value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Value)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getWith_Value()
   * @model containment="true"
   * @generated
   */
  Value getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.With#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Value value);

} // With
