/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.seleniumScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Write Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.seleniumScript.WriteAction#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.seleniumScript.WriteAction#getSelector <em>Selector</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getWriteAction()
 * @model
 * @generated
 */
public interface WriteAction extends Action
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getWriteAction_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.WriteAction#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(SelectorWith)
   * @see org.xtext.example.seleniumScript.SeleniumScriptPackage#getWriteAction_Selector()
   * @model containment="true"
   * @generated
   */
  SelectorWith getSelector();

  /**
   * Sets the value of the '{@link org.xtext.example.seleniumScript.WriteAction#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(SelectorWith value);

} // WriteAction
