/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SeleniumScriptStandaloneSetup extends SeleniumScriptStandaloneSetupGenerated {

	public static void doSetup() {
		new SeleniumScriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
